<figure class="group relative grid overflow-hidden bg-container-darker text-white isolate">
    <img
        src="https://unsplash.com/photos/F7D7oWb8aO0/download?force=true&auto=format&fit=crop&w=1200&q=80"
        alt="Hit the court in style"
        width="1400"
        height="800"
        loading="lazy"
        class="col-start-1 row-start-1 w-full h-[600px] sm:h-[800px] md:h-[576px] object-cover group-hover:opacity-70 transition-opacity duration-500"
    >
    <figcaption class="z-10 col-start-1 row-start-1 self-end p-6 pt-28 bg-gradient-to-t from-gray-800/75 text-2xl font-medium">
        <p class="mb-2 text-6xl font-bold text-balance">Hit the court in style.</p>
        <p>
            <a
                href="{{store url='home'}}"
                class="before:absolute before:inset-0"
            >
                Shop our tennis gear →
            </a>
        </p>
    </figcaption>
</figure>
