<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var HyvaCsp $hyvaCsp */

// Remove any child blocks that don't need to be part of the footer columns
$footerColumns = array_diff(
    $block->getChildNames(),
    array('footer-copyright', 'form.subscribe', 'footer-content-before', 'footer-content-after')
);
?>

<?= $block->getChildHtml('footer-content-before') ?>
<?= $block->getChildHtml('subscribe') ?>
<div class="bg-zinc-100 border-t border-zinc-200">
    <div class="container py-8 mx-auto">
        <div class="grid grid-cols-1 lg:grid-cols-4 lg:gap-6 text-slate-600">
            <?php foreach ($footerColumns as $childName): ?>
                <?= $block->getBlockHtml($childName) ?>
            <?php endforeach; ?>
        </div>
    </div>
    <div class="space-y-10 bg-zinc-50 py-4">
        <div class="container py-8 flex gap-4 flex-wrap justify-center" aria-label="Payment Providers">
            <a href="https://armyshop.rs/trust/">
                <img title="trustmark" src="https://verify.etrustmark.rs/cert/image.php" alt="trustmark" width="279" height="94" />
            </a>
            <a href="https://rs.visa.com/pay-with-visa/security-and-assistance/protected-everywhere.html" target="_blank" rel="noopener">
                <img src="https://armyshop.rs/wp-content/uploads/2024/09/visa-secure.jpeg" alt="visa" width="51" height="51" />
            </a>
            <a href="http://www.mastercard.com/rs/consumer/credit-cards.html" target="_blank" rel="noopener">
                <img src="https://armyshop.rs/wp-content/uploads/2024/09/mastercard-id-check.svg" alt="master" width="68" height="51" />
            </a>
            <a href="https://www.bancaintesa.rs/pocetna.1.html" target="_blank" rel="noopener">
                <img src="https://armyshop.rs/wp-content/uploads/2024/09/BankaIntesa.svg" alt="bancaintesa" width="242" height="32" />
            </a>
            <img src="https://armyshop.rs/wp-content/uploads/2024/09/visa-1.png" alt="visa" width="83" height="25" />
            <img src="https://armyshop.rs/wp-content/uploads/2023/04/mc_acc_opt_70_1x.png" alt="mc" width="69" height="43"/>
            <img src="https://armyshop.rs/wp-content/uploads/2023/04/ms_acc_opt_70_1x.png" alt="mc" width="69" height="43" />
            <img src="https://armyshop.rs/wp-content/uploads/2024/09/dina-card.png" alt="dinacard" width="69" height="43" />
            <img src="https://armyshop.rs/wp-content/uploads/2024/09/american-express.png" alt="american" width="48" height="24" />
            <a href="https://www.wspay.rs/" target="_blank" rel="noopener">
                <img src="https://armyshop.rs/wp-content/uploads/2024/09/ws-pay.svg" alt="wspay" width="96" height="45" />
            </a>
        </div>
    </div>

    <div class="container pt-7 pb-5 border-t border-zinc-200 flex justify-between items-center flex-col sm:flex-row text-sm">
        <?= $block->getChildHtml('copyright') ?>
        <nav class="text-slate-600" aria-label="<?= $escaper->escapeHtml(__('Legal Menu')) ?>">
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('privacy-policy-cookie-restriction-mode')) ?>"
                class="inline-block py-1 px-2 sm:px-0 sm:mr-4 sm:last:mr-0 hover:underline"
            ><?= $escaper->escapeHtml(__('Terms & Conditions')) ?></a>
            <a
                href="<?= $escaper->escapeUrl($block->getUrl('privacy-policy-cookie-restriction-mode')) ?>"
                class="inline-block py-1 px-2 sm:px-0 sm:mr-4 sm:last:mr-0 hover:underline"
            ><?= $escaper->escapeHtml(__('Privacy Policy')) ?></a>
        </nav>
    </div>
</div>
<script>
    function mobileFooterCollpase() {
        return {
            open: false,
            isMobile: false,
            init() {
                this.checkIsMobileResolution();
                if (this.$root.dataset.open === "true") {
                    this.open = true;
                }
            },
            checkIsMobileResolution() {
                this.isMobile = getComputedStyle(this.$refs.toggleIcon).display !== 'none'
            },
            isOpen() {
                return this.isMobile ? this.open : true;
            },
            toggle() {
                return this.isMobile ? this.open = !this.open : true;
            },
            eventListeners: {
                ['@resize.window.debounce']() {
                    this.checkIsMobileResolution();
                },
                ['@visibilitychange.window.debounce']() {
                    this.checkIsMobileResolution();
                }
            },
            setToggleRoles: {
                [':role']() {
                    return this.isMobile && 'button';
                },
                [':tabindex']() {
                    return this.isMobile && '0';
                },
                [':aria-expanded']() {
                    return this.isMobile ? this.open : null;
                },
                [':aria-controls']() {
                    return this.isMobile ? this.$el.dataset.id : null;
                }
            },
            setCollapseRoles: {
                [':aria-hidden']() {
                    return this.isMobile ? !this.open : null;
                },
                [':aria-labelledby']() {
                    return this.isMobile ? this.$el.id : null;
                }
            }
        }
    }
    window.addEventListener('alpine:init', () => Alpine.data('mobileFooterCollpase', mobileFooterCollpase), { once: true })
</script>
<?php $hyvaCsp->registerInlineScript() ?>

