<div class="relative grid lg:grid-cols-[minmax(auto,_1fr)_488px] h-[640px] sm:h-[720px] lg:h-[880px]">
    <img
        alt="A runner tying his shoes"
        class="row-start-1 col-start-1 h-full w-full object-cover"
        src="https://unsplash.com/photos/d3bYmnZ0ank/download?force=true&auto=format&fit=crop&w=1228&q=80"
        width="1228"
        height="768"
        loading="lazy"
    >
    <div class="row-start-1 col-start-1 flex flex-col justify-end py-8 sm:py-12 px-6 sm:px-12 lg:justify-center lg:col-start-2
        bg-gradient-to-t from-slate-800/75 text-white lg:bg-none lg:bg-blue-800">
        <p class="mb-4 sm:mb-6 text-4xl sm:text-6xl xl:text-7xl leading-none font-bold drop-shadow-lg text-center lg:text-left">
            Excuses don’t burn calories
        </p>
        <p class="text-lg sm:text-2xl font-medium text-center lg:text-left">
            Make sure each work-out is better than the last with our ProFit collection.
        </p>
        <div class="mt-8 sm:mt-12 flex flex-col gap-3 sm:flex-row sm:justify-center lg:flex-col lg:justify-start">
            <a
                href="{{store url='home'}}"
                class="group btn gap-2 justify-between rounded-md py-3 px-6 text-base sm:text-lg shadow-none hover:shadow-lg active:shadow transition
                    bg-white text-blue-700 border border-blue-400 hover:bg-white focus:ring-blue-200"
            >
                <span>Shop Men</span>
                <svg xmlns="http://www.w3.org/2000/svg" class="transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                </svg>
            </a>
            <a
                href="{{store url='home'}}"
                class="group btn gap-2 justify-between rounded-md py-3 px-6 text-base sm:text-lg shadow-none hover:shadow-lg active:shadow transition
                    bg-white text-blue-700 border border-blue-400 hover:bg-white focus:ring-blue-200"
            >
                <span>Shop Women</span>
                <svg xmlns="http://www.w3.org/2000/svg" class="transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                </svg>
            </a>
        </div>
    </div>
</div>
