<div class="relative">
    <img
        alt="A runner tying his shoes"
        class="absolute h-full w-full object-cover"
        src="https://unsplash.com/photos/d3bYmnZ0ank/download?force=true&auto=format&fit=crop&w=1228&q=80"
        width="1228"
        height="768"
        loading="lazy"
    >
    <div class="relative bg-gray-800/70 py-80 px-8">
        <div class="max-w-lg mx-auto flex flex-col gap-10">
            <div class="text-4xl leading-10 font-bold text-white drop-shadow-lg text-center md:text-6xl lg:text-7xl">
                Excuses don’t burn calories
            </div>
            <div class="text-2xl leading-8 font-semibold text-white text-center">
                Make sure each work-out is better than the last with our ProFit collection.
            </div>
            <div class="flex flex-col gap-4 sm:flex-row sm:justify-center">
                <a
                    href="{{store url='home'}}"
                    class="group btn gap-2 justify-between rounded-md py-3 px-6 text-base shadow-none hover:shadow-lg active:shadow transition
                        bg-blue-600 text-white border border-transparent hover:bg-blue-700 focus:ring-blue-200 active:bg-blue-700"
                >
                    <span>Shop Men</span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                    </svg>
                </a>
                <a
                    href="{{store url='home'}}"
                    class="group btn gap-2 justify-between rounded-md py-3 px-6 text-base shadow-none hover:shadow-lg active:shadow transition
                        bg-blue-600 text-white border border-transparent hover:bg-blue-700 focus:ring-blue-200 active:bg-blue-700"
                >
                    <span>Shop Women</span>
                    <svg xmlns="http://www.w3.org/2000/svg" class="transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2">
                        <path stroke-linecap="round" stroke-linejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                    </svg>
                </a>
            </div>
        </div>
    </div>
</div>
