<div class="relative bg-blue-900 py-24 px-8">
    <div class="max-w-lg mx-auto flex flex-col gap-10">
        <div class="text-4xl leading-10 font-bold text-white drop-shadow-lg text-center md:text-6xl lg:text-7xl">
            Excuses don’t burn calories
        </div>
        <div class="text-2xl leading-8 font-semibold text-white text-center">
            Make sure each work-out is better than the last with our ProFit collection.
        </div>
        <div class="flex flex-col gap-4 sm:flex-row sm:justify-center">
            <a
                href="{{store url='home'}}"
                class="group btn gap-2 justify-between rounded-md py-3 px-6 text-base shadow-none hover:shadow-lg active:shadow transition
                    bg-white text-blue-700 border border-blue-400 hover:bg-white focus:ring-blue-200"
            >
                <span>Shop Men</span>
                <svg xmlns="http://www.w3.org/2000/svg" class="transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                </svg>
            </a>
            <a
                href="{{store url='home'}}"
                class="group btn gap-2 justify-between rounded-md py-3 px-6 text-base shadow-none hover:shadow-lg active:shadow transition
                    bg-white text-blue-700 border border-blue-400 hover:bg-white focus:ring-blue-200"
            >
                <span>Shop Women</span>
                <svg xmlns="http://www.w3.org/2000/svg" class="transition-transform group-hover:translate-x-1" fill="none" viewBox="0 0 24 24" width="20" height="20" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M14 5l7 7m0 0l-7 7m7-7H3" />
                </svg>
            </a>
        </div>
    </div>
</div>
