<div class="grid grid-cols-2 md:grid-cols-4 gap-4">
    <figure class="group relative grid overflow-hidden bg-container-darker text-white isolate">
        <img
            src="https://unsplash.com/photos/v0f_sspLB-o/download?force=true&w=664&q=80"
            alt="A woman stretching after a run"
            width="320"
            height="320"
            loading="lazy"
            class="col-start-1 row-start-1 w-full h-56 sm:h-80 xl:h-96 object-cover group-hover:opacity-70 transition-opacity duration-500"
        >
        <figcaption class="z-10 col-start-1 row-start-1 self-end p-7 pt-1 bg-gradient-to-t from-gray-800/75 text-lg font-bold text-center">
            <p>
                <a href="https://d.mage-ui.test/home/" class="before:absolute before:inset-0">Women</a>
            </p>
        </figcaption>
    </figure>
    <figure class="group relative grid overflow-hidden bg-container-darker text-white isolate">
        <img
            src="https://unsplash.com/photos/dCL6vpW8oJM/download?force=true&w=664&q=80"
            alt="A man in a hoodie and cap walking away"
            width="320"
            height="320"
            loading="lazy"
            class="col-start-1 row-start-1 w-full h-56 sm:h-80 xl:h-96 object-cover group-hover:opacity-70 transition-opacity duration-500"
        >
        <figcaption class="z-10 col-start-1 row-start-1 self-end p-7 pt-1 bg-gradient-to-t from-gray-800/75 text-lg font-bold text-center">
            <p>
                <a href="https://d.mage-ui.test/home/" class="before:absolute before:inset-0">Men</a>
            </p>
        </figcaption>
    </figure>
    <figure class="group relative grid overflow-hidden bg-container-darker text-white isolate">
        <img
            src="https://unsplash.com/photos/SdmdP3UKE6g/download?force=true&w=664&q=80"
            alt="A woman showing her sports watch"
            width="320"
            height="320"
            loading="lazy"
            class="col-start-1 row-start-1 w-full h-56 sm:h-80 xl:h-96 object-cover group-hover:opacity-70 transition-opacity duration-500"
        >
        <figcaption class="z-10 col-start-1 row-start-1 self-end p-7 pt-1 bg-gradient-to-t from-gray-800/75 text-lg font-bold text-center">
            <p>
                <a href="https://d.mage-ui.test/home/" class="before:absolute before:inset-0">Gear</a>
            </p>
        </figcaption>
    </figure>
    <figure class="group relative grid overflow-hidden bg-container-darker text-white isolate">
        <img
            src="https://unsplash.com/photos/2mGaIs51MNU/download?force=true&w=664&q=80"
            alt="A woman making a knee kick in the air"
            width="320"
            height="320"
            loading="lazy"
            class="col-start-1 row-start-1 w-full h-56 sm:h-80 xl:h-96 object-cover group-hover:opacity-70 transition-opacity duration-500"
        >
        <figcaption class="z-10 col-start-1 row-start-1 self-end p-7 pt-1 bg-gradient-to-t from-gray-800/75 text-lg font-bold text-center">
            <p>
                <a href="https://d.mage-ui.test/home/" class="before:absolute before:inset-0">Training</a>
            </p>
        </figcaption>
    </figure>
</div>
