<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\BlockJsDependencies;
use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Catalog\Block\Product\Image;
use Magento\Framework\Escaper;

/** @var Image $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */

$pageJsRegistry = $viewModels->require(BlockJsDependencies::class);
$pageJsRegistry->setBlockTemplateDependency($block, 'Magento_Catalog::product/list/js/image.phtml');

$hasLoadingAttribute = ($block->getCustomAttributes() ?: [])['loading'] ?? false;

?>
<img class="<?= $escaper->escapeHtmlAttr($block->getClass()) ?>"
     x-data="initProductItemImage"
     @update-gallery-<?= (int)$block->getProductId() ?>.window="updateImage"
    <?php foreach ($block->getCustomAttributes() as $name => $value): ?>
        <?= $escaper->escapeHtmlAttr($name) ?>="<?= $escaper->escapeHtmlAttr($value) ?>"
    <?php endforeach; ?>
    src="<?= $escaper->escapeUrl($block->getImageUrl()) ?>"
    <?php if (! $hasLoadingAttribute): ?>
    loading="lazy"
    <?php endif; ?>
    width="<?= $escaper->escapeHtmlAttr($block->getWidth()) ?>"
    height="<?= $escaper->escapeHtmlAttr($block->getHeight()) ?>"
    alt="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
    title="<?= $escaper->escapeHtmlAttr($block->getLabel()) ?>"
>
