<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\ViewModel\HyvaCsp;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var HyvaCsp $hyvaCsp */

?>
<script>
    function initSwatchOptions(swatchConfig) {
        return {
            swatchConfig,
            getAttributeSwatchData(attributeId) {
                const swatchConfig = Object.assign({}, this.swatchConfig[attributeId]);
                swatchConfig['details'] = JSON.parse(swatchConfig['additional_data']);

                return swatchConfig;
            },
            mapSwatchTypeNumberToTypeCode(typeNumber) {
                switch ("" + typeNumber) {
                    case "1":
                        return "color"
                    case "2":
                        return "image"
                    case "3":
                        return "empty"
                    case "0":
                    default:
                        return "text"
                }
            },
            getTypeOfFirstOption(attributeId) {
                for (const optionId in this.swatchConfig[attributeId]) {
                    const option = this.swatchConfig[attributeId][optionId];
                    if (typeof option.type !== 'undefined') {
                        return this.mapSwatchTypeNumberToTypeCode(option.type);
                    }
                }
            },
            getVisualSwatchType(attributeId, targetOptionId) {
                // If a type configuration is present for the given option id, use it
                const config = this.swatchConfig[attributeId];
                if (config[targetOptionId] && typeof config[targetOptionId].type !== 'undefined') {
                    return this.mapSwatchTypeNumberToTypeCode(config[targetOptionId].type);
                }

                // Otherwise - if no config is present for the target option - use the type of the first option
                // with a type property from the attribute, thus assuming its the same type as the target option.
                // (This edge case condition can occur on single swatch products if some options are not salable)
                return this.getTypeOfFirstOption(attributeId);
            },
            getSwatchType(attributeId, optionId) {
                // Deserialize the attribute details the first time they are used
                if (this.swatchConfig[attributeId] && ! this.swatchConfig[attributeId].details) {
                    this.swatchConfig[attributeId] = this.getAttributeSwatchData(attributeId);
                }
                const type =  this.swatchConfig[attributeId] &&
                    this.swatchConfig[attributeId].details &&
                    this.swatchConfig[attributeId].details.swatch_input_type ||
                    "empty";
                return type === 'visual' ? this.getVisualSwatchType(attributeId, optionId) : type;
            },
            isTextSwatch() {
                const attributeId = this.getDataAttributeId(this.$el);
                return this.getSwatchType(attributeId, this.item.id) === 'text';
            },
            isColorSwatch() {
                const attributeId = this.getDataAttributeId(this.$el);
                return this.getSwatchType(attributeId, this.item.id) === 'color';
            },
            isImageSwatch() {
                const attributeId = this.getDataAttributeId(this.$el);
                return this.getSwatchType(attributeId, this.item.id) === 'image';
            },
            isVisualSwatch() {
                const attributeId = this.activeTooltipItem.attribute;
                const type = this.getSwatchType(attributeId, this.activeTooltipItem.item);

                return ['image', 'color'].includes(type);
            },
            getSwatchBackgroundStyle() {
                const attributeId = this.getDataAttributeId(this.$el);
                const config = this.getSwatchConfig(attributeId, this.item.id);
                const type = this.getSwatchType(attributeId, this.item.id);

                if (type === "color") {
                        return 'background-color:' + config.value;
                } else if (type === "image") {
                        return "background: #ffffff url('" + config.value + "') no-repeat center";
                } else {
                    return '';
                }
            },
            getSwatchText() {
                const attributeId = this.getDataAttributeId(this.$el);
                const optionId = this.$el.dataset.optionId || this.selectedValues[attributeId];
                const config = this.getSwatchConfig(attributeId, optionId);
                return config.label || config.value || this.getOptionLabelFromOptionConfig(attributeId, optionId);
            },
            getOptionLabelFromOptionConfig(attributeId, optionId) {
                // Fallback if no value is present in swatchConfig data
                // Reference issue https://gitlab.hyva.io/hyva-themes/magento2-default-theme/-/issues/190
                const option = this.getAllAttributeOptions(attributeId).filter(option => option.id === optionId);
                return option && option[0] && option[0].label ||'';
            },
            getSwatchConfig(attributeId, optionId) {
                return this.swatchConfig[attributeId] && this.swatchConfig[attributeId][optionId]
                    ? this.swatchConfig[attributeId][optionId]
                    : false;
            },
            activeTooltipItem: false,
            tooltipPositionElement: false,
            isTooltipVisible() {
                return this.activeTooltipItem &&
                    this.getSwatchConfig(
                        this.activeTooltipItem.attribute,
                        this.activeTooltipItem.item
                    );
            },
            isFirstItemCol() {
                return this.activeTooltipItem.index === 0;
            },
            getTooltipImageStyle() {
                const attributeId = this.activeTooltipItem.attribute;
                const optionId = this.activeTooltipItem.item;
                const config = this.getSwatchConfig(attributeId, optionId);
                const type = this.getSwatchType(attributeId, optionId);

                if (type === "color") {
                    return 'background-color:' + config.value + '; width: 110px; height: 90px;';
                } else if (type === "image") {
                    return "background: #ffffff url('" + config.thumb +
                        "') center center no-repeat; width: 110px; height: 90px;";
                } else {
                    return 'display:none';
                }
            },
            getTooltipWrapperClasses() {
                return {
                    '-translate-x-5': this.isFirstItemCol()
                }
            },
            getTooltipPosition() {
                return this.tooltipPositionElement ?
                    `top: ${this.tooltipPositionElement.offsetTop}px;` +
                    `left: ${
                        this.tooltipPositionElement.offsetLeft - (
                            this.tooltipPositionElement.closest('.snap') &&
                            this.tooltipPositionElement.closest('.snap').scrollLeft ||
                            0
                        )
                    }px;` : ''
            },
            getTooltipLabel() {
                return this.getSwatchConfig(this.activeTooltipItem.attribute, this.activeTooltipItem.item).label
            },
            focusedLabel: false,
            focusLabel(optionId) {
                this.focusedLabel = optionId;
            },
            blurLabel() {
                this.focusedLabel = false;
            },
            showSwatches: false,
            initShowSwatchesIntersect() {
                if ('IntersectionObserver' in window && !window.scrollY) {
                    let io = new IntersectionObserver(
                        entries => {
                            entries.map(entry => {
                                if (entry.isIntersecting) {
                                    this.showSwatches = true;
                                    io.unobserve(this.$root);
                                }
                            })
                        }
                    );
                    io.observe(this.$root);
                } else {
                    this.showSwatches = true
                }
            },
            getSwatchOptionHtmlId() {
                const productId = this.$el.closest('[data-product-id]').dataset.productId;
                return this.$id(`attribute-option-${productId}-${this.item.id}`)
            },
            getSwatchOptionHtmlIdGroup() {
                const productId = this.$el.closest('[data-product-id]').dataset.productId;
                return [`attribute-option-${productId}-${this.item.id}`];
            },
            swatchOptionClasses() {
                const attributeId = this.getDataAttributeId(this.$el);
                return {
                    'border-container-lighter ring ring-primary/50': (this.selectedValues[attributeId] === this.item.id),
                    'border-container-darker': (this.selectedValues[attributeId] !== this.item.id),
                    'w-6 h-6': !this.isTextSwatch(),
                    'border-container-lighter ring ring-primary/75': this.focusedLabel === this.item.id,
                }
            },
            outOfStockSwatchWrapperClasses() {
                return {
                    'w-6 h-6': !this.isTextSwatch(),
                }
            },
            outOfStockSwatchContentClasses() {
                return {
                    'sr-only': !this.isTextSwatch()
                };
            },
            setActiveTooltipItem() {
                this.activeTooltipItem = {
                    attribute: this.getDataAttributeId(this.$el),
                    item: this.item.id,
                    index: this.index
                };
                this.tooltipPositionElement = this.$event.target;
            },
            unsetActiveTooltipItem() {
                this.activeTooltipItem = false;
            },
            onFocusSwatchItem() {
                this.focusLabel(this.item.id);
            },
            isSwatchRequired() {
                const attributeId = this.getDataAttributeId(this.$el);
                return this.getAllowedAttributeOptions(attributeId)
                    .filter(attributeOption => this.selectedValues[attributeOption])
                    .length === 0
            },
            modelBinding() {
                const attributeId = this.getDataAttributeId(this.$el);
                return this.selectedValues[attributeId];
            },
            setClassesByType() {
                const { classText, classColor, classImage } = this.$el.dataset;

                if (this.isTextSwatch()) return classText;
                if (this.isColorSwatch()) return classColor;
                if (this.isImageSwatch()) return classImage;
            }
        }
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>
