<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Swatches\Block\LayeredNavigation\RenderLayered;
use Magento\Swatches\ViewModel\Product\Renderer\Configurable as ConfigurableViewModel;

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var RenderLayered $block */
/** @var SecureHtmlRenderer $secureRenderer */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ConfigurableViewModel $configurableViewModel */
$configurableViewModel = $viewModels->require(ConfigurableViewModel::class);

$swatchData = $block->getSwatchData();

$swatchClasses = "swatch-option-link-layered swatch-option bg-white flex justify-center text-slate-800 font-medium transition outline-none";

$textSwatchClasses = "type-text py-2 px-2.5 !border-2 rounded-md border-slate-200 text-sm font-medium" // standard
    . " hover:border-blue-300 focus:border-blue-300" // hover - focus
    . " data-[checked]:focus:border-blue-400 data-[checked]:focus:ring data-[checked]:focus:ring-blue-100" // focus+selected
    . " data-[checked]:border-blue-500 [&[data-checked]:not(:focus)]:bg-blue-50 data-[checked]:text-blue-800" // selected
    . " active:border-blue-500"; // active

$colorSwatchClasses = "type-color w-8 h-8 !mr-2 !min-w-0 rounded-full !border-0" // standard
    . " shadow-[inset_0_0_0_1px_rgba(0,0,0,0.32)]" // border
    . " hover:ring-2 hover:ring-blue-300 [&:hover:not([data-checked])]:ring-offset-2" // hover
    . " focus:ring-2 focus:ring-blue-300 [&:focus:not([data-checked])]:ring-offset-2" // focus
    . " data-[checked]:focus:ring-2 data-[checked]:focus:ring-blue-500 data-[checked]:focus:ring-offset-2 data-[checked]:focus:ring-offset-blue-200" // focus+selected
    . " data-[checked]:ring-2 data-[checked]:ring-blue-500 [&[data-checked]:not(:focus)]:ring-offset-2" // selected
    . " active:ring-2 active:ring-blue-500 [&:active:not([data-checked])]:ring-offset-2"; // active

$imageSwatchClasses = "type-image w-8 h-8 !mr-2 border-slate-200 !p-0 rounded-md aspect-square !border-2 !min-w-0" // standard
    . " focus:ring-2 focus:ring-blue-300 [&:focus:not([data-checked])]:ring-offset-2" // focus
    . " hover:ring-2 hover:ring-blue-300 [&:hover:not([data-checked])]:ring-offset-2" // hover
    . " data-[checked]:focus:ring-2 data-[checked]:focus:ring-blue-500 data-[checked]:focus:ring-offset-2 data-[checked]:focus:ring-offset-blue-200" // focus+selected
    . " data-[checked]:ring-2 data-[checked]:ring-blue-500 [&[data-checked]:not(:focus)]:ring-offset-2" // selected
    . " active:ring-2 active:ring-blue-500 [&:active:not([data-checked])]:ring-offset-2"; // active
?>

<script>
    function initLayeredSwatch_<?= $escaper->escapeJs($swatchData['attribute_code']) ?>() {
        return {
            getSwatchType(typeNumber) {
                switch ("" + typeNumber) {
                    case "1":
                        return "color"
                    case "2":
                        return "image"
                    case "0":
                    default:
                        return "text"
                }
            },
            activeTooltipItem: false,
            tooltipPositionElement: false,
            isTooltipVisible() {
                return this.activeTooltipItem
            },
            isFirstItemCol() {
                const left = this.tooltipPositionElement.offsetLeft;
                const leftParent = this.tooltipPositionElement.parentNode.offsetLeft;
                const width = this.tooltipPositionElement.offsetWidth;
                return left - leftParent < width;
            },
            getTooltipImageStyle() {
                const type = this.activeTooltipItem.type;

                if (this.getSwatchType(type) === "color") {
                    return 'background-color:' + this.activeTooltipItem.value + '; width: 110px; height: 90px;';
                } else if (this.getSwatchType(type) === "image") {
                    return "background: #fff url('" + this.activeTooltipItem.thumb +
                        "') center center no-repeat; width: 110px; height: 90px;";
                } else {
                    return 'display:none';
                }
            },
            getTooltipPosition() {
                return this.tooltipPositionElement ?
                    (
                        `top: ${this.tooltipPositionElement.offsetTop}px;` +
                        `left: ${this.tooltipPositionElement.offsetLeft}px;`
                    ) : ''
            },
            getTooltipLabel() {
                return this.activeTooltipItem.label || ''
            },
            isVisualSwatch() {
                return this.getSwatchType(this.activeTooltipItem.type) !== 'text'
            }
        }
    }
</script>

<div
    class="swatch-attribute swatch-layered <?= $escaper->escapeHtmlAttr($swatchData['attribute_code']) ?>"
    x-data="initLayeredSwatch_<?= $escaper->escapeJs($swatchData['attribute_code']) ?>()"
    x-defer="intersect"
>
    <div class="swatch-attribute-options gap-2">
        <?php foreach ($swatchData['options'] as $option => $label): ?>
            <?php
            // check required if attribute property "is_filterable" is set to "Filterable (no results)"
            if (!isset($swatchData['swatches'][$option])) {
                continue;
            }

            $swatchType = (string) $swatchData['swatches'][$option]['type'];
            $swatchValue = (string) $swatchData['swatches'][$option]['value'];
            $isVisualSwatch = $swatchType === "1" || $swatchType === "2";
            $elasticsuiteStyle = $label['custom_style'];
            $elasticsuiteSelected = str_contains($elasticsuiteStyle, 'selected');
            ?>
            <a
                href="<?= $escaper->escapeUrl($label['link']) ?>" rel="nofollow"
                aria-label="<?= $escaper->escapeHtmlAttr(
                    __('Filter %1 %2', $swatchData['attribute_label'], $label['label']) .
                    ($elasticsuiteSelected ? ', ' . __('filter selected') : '')
                ) ?>"
                <?php if($swatchType === '1'): // Color Swatch ?>
                    style="background-color: <?= $swatchValue ?>"
                    class="<?= $escaper->escapeHtmlAttr($swatchClasses . " " . $colorSwatchClasses) ?>"
                <?php elseif ($swatchType === '2'): // Image Swatch ?>
                    style="background: #fff url('<?= $escaper->escapeUrl($block->getSwatchPath('swatch_image', $swatchValue)) ?>') center no-repeat"
                    class="<?= $escaper->escapeHtmlAttr($swatchClasses . " " . $imageSwatchClasses) ?>"
                <?php else: // Default / Text Swatch ?>
                    class="<?= $escaper->escapeHtmlAttr($swatchClasses . " " . $textSwatchClasses) ?>"
                <?php endif; ?>
                <?php if ($elasticsuiteSelected): ?>
                    data-checked
                <?php endif; ?>
                <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
                    <?php $swatchThumbPath = $block->getSwatchPath('swatch_thumb', $swatchValue); ?>
                    @mouseenter.self="
                        activeTooltipItem = {
                            attribute: '<?= $escaper->escapeHtmlAttr($swatchValue) ?>',
                            type: '<?= $escaper->escapeHtmlAttr($swatchType) ?>',
                            id: '<?= $escaper->escapeHtmlAttr($option) ?>',
                            label: '<?= $escaper->escapeHtmlAttr($label['label']) ?>',
                            thumb: '<?= $escaper->escapeUrl($swatchThumbPath) ?>',
                            value: '<?= $escaper->escapeHtmlAttr($swatchValue) ?>'
                        };
                        tooltipPositionElement = $event.target;"
                    @mouseleave.self="activeTooltipItem = false"
                <?php endif; ?>
            >
                <?php if (!$isVisualSwatch): ?>
                    <?= $escaper->escapeHtml($swatchValue ?: $label['label']) ?>
                <?php endif; ?>
            </a>
        <?php endforeach; ?>
    </div>
    <?php if ($configurableViewModel->getShowSwatchTooltip()): ?>
        <?= /* @noEscape */ $block->getBlockHtml('product.swatch.tooltip'); ?>
    <?php endif; ?>
</div>
