<figure class="group relative grid overflow-hidden bg-container-darker text-white isolate">
    <div class="flex col-start-1 row-start-1 w-full h-[600px] sm:h-[800px] md:h-[576px] group-hover:opacity-70 transition-opacity duration-500">
        <img
            src="https://unsplash.com/photos/F7D7oWb8aO0/download?force=true&auto=format&fit=crop&w=800&q=80"
            alt="Tennis player laying on the court"
            width="600"
            height="600"
            loading="lazy"
            class="w-full md:w-1/2 h-full object-cover"
        >
        <img
            src="https://unsplash.com/photos/uZmr0wwfHNA/download?force=true&auto=format&fit=crop&w=800&q=80"
            alt="Tennis racket on the tennis field"
            width="600"
            height="600"
            loading="lazy"
            class="hidden md:block md:w-1/2 h-full object-cover"
        >
    </div>
    <figcaption class="z-10 col-start-1 row-start-1 self-end p-6 pt-28 bg-gradient-to-t from-gray-800/75 text-2xl font-medium">
        <p class="mb-2 text-6xl font-bold text-balance">Hit the court in style.</p>
        <p>
            <a href="https://b.mage-ui.test/home/" class="before:absolute before:inset-0">Shop our tennis gear</a>
        </p>
    </figcaption>
</figure>
